#!/usr/bin/env npx tsx
/**
 * buildData.ts — 从 nihaisha-nishi-tcm Markdown 解析生成 TypeScript 数据文件
 * 用法: npx tsx scripts/buildData.ts [nihaisha-repo-path]
 */

import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const NIHAISHA = process.argv[2] || "/tmp/nihaisha-nishi-tcm";
const REF = path.join(NIHAISHA, "references");
const OUT = path.join(__dirname, "..", "src", "data");

// ── helpers ──────────────────────────────────────────────

const r = (f: string) => {
  const p = path.join(REF, f);
  return fs.existsSync(p) ? fs.readFileSync(p, "utf-8") : "";
};

const S = JSON.stringify;

function wr(fname: string, imp: string, body: string) {
  const txt = `// Auto-generated by scripts/buildData.ts\n${imp}\n${body}\n`;
  fs.writeFileSync(path.join(OUT, fname), txt, "utf-8");
  const n = body.split("\n").filter((l) => l.trim()).length;
  console.log(`  ✓ ${fname} (${n} entries)`);
}

function parseTable(md: string): string[][] {
  const rows: string[][] = [];
  for (const line of md.split("\n")) {
    const t = line.trim();
    if (!t.startsWith("|")) continue;
    if (/^\|[\s\-:|]+\|$/.test(t)) continue;
    const cells = t.split("|").slice(1, -1).map((c) => c.trim());
    if (cells.length >= 2) rows.push(cells);
  }
  return rows;
}

const HIGH = ["附子","四逆","大承气","抵当","大陷胸","癌症","肿瘤","阴实","妊娠","孕妇","儿童","小儿"];
const MED = ["麻黄","大黄","芒硝","甘遂","芫花","大戟"];
function risk(s: string): string {
  if (HIGH.some((k) => s.includes(k))) return "high";
  if (MED.some((k) => s.includes(k))) return "medium";
  return "low";
}

// ── 1. Formulas ───────────────────────────────────────────

function buildFormulas() {
  const md = r("formula-patterns.md");
  const sections = md.split("\n## ");
  const out: Record<string, any>[] = [];
  let n = 0;

  for (const sec of sections) {
    const rows = parseTable(sec);
    const hdr = rows.find((r) => r[0] === "方剂" || r.some((c) => c.includes("方剂")));
    if (!hdr) continue;

    const hi = hdr.findIndex((c) => c === "方剂" || c.includes("方剂"));
    const zi = hdr.findIndex((c) => c.includes("课程方证") || (c.includes("方证") && !c.includes("课")) || c === "主症" || c.includes("主治"));
    const di = hdr.findIndex((c) => c.includes("鉴别") || c.includes("区别"));
    const li = hdr.findIndex((c) => c === "课次" || (c.includes("课次") && !c.includes("方证")));
    const secName = sec.split("\n")[0].replace(/^#+\s*/, "").trim();

    const hi2 = rows.indexOf(hdr);
    for (let i = hi2 + 1; i < rows.length; i++) {
      const r = rows[i];
      if (r.length < 2) continue;
      const name = r[hi] || "";
      if (!name || name === "方剂" || name.includes("---")) continue;

      const z = zi >= 0 ? r[zi] || "" : "";
      const d = di >= 0 ? r[di] || "" : "";
      const l = li >= 0 ? r[li] || "" : "";
      const sym = z.split(/[，,；;]/).map((s) => s.trim()).filter(Boolean).slice(0, 5);

      out.push({
        id: `f-${name.replace(/[（）()\s\/]/g,"").toLowerCase()}-${++n}`,
        name, source: "《伤寒论》", composition: [],
        symptoms: sym, syndromes: [secName],
        pathology: z, explanation: d,
        usage: l ? `涉及课次: ${l}` : "",
        riskLevel: risk(name + z + d),
        lessonRef: l,
      });
    }
  }

  const items = out.map((f) => `
  { id:${S(f.id)}, name:${S(f.name)}, source:${S(f.source)}, composition:[],
    symptoms:[${f.symptoms.map((s: string) => S(s)).join(",")}],
    syndromes:[${f.syndromes.map((s: string) => S(s)).join(",")}],
    pathology:${S(f.pathology)}, explanation:${S(f.explanation)},
    usage:${S(f.usage)}, riskLevel:${S(f.riskLevel)}, lessonRef:${S(f.lessonRef)} }`);

  wr("formulas.ts", 'import { Formula } from "../types";\n', `export const formulas: Formula[] = [${items.join(",")}\n];`);
}

// ── 2. Lessons + Chapters ────────────────────────────────

function buildLessons() {
  const md = r("lesson-map.md");

  // chapters from module distribution
  const modSec = md.split("## 模块分布")[1]?.split("## ")[0] || "";
  const chs: Record<string, any>[] = [];
  let ci = 0;
  for (const line of modSec.split("\n")) {
    const m = line.match(/- 模块[一二三四五六七八九十]+[：:]\s*(.+?)[：:]\s*(.+)/);
    if (m) chs.push({ id: `ch-${++ci}`, title: m[1].trim(), order: ci, description: m[2].trim(), range: m[2].trim() });
  }

  // lesson table
  const tbl = md.split("## 逐课详表")[1]?.split("## ")[0] || "";
  const trs = parseTable(tbl);
  const lss: Record<string, any>[] = [];
  let sq = 0;
  for (const r of trs) {
    if (r[0] === "课次" || !r[0] || r[0].length < 2) continue;
    const nm = r[0].trim();
    lss.push({ id: `l-${nm.replace(/\s/g,"").toLowerCase()}`, chapterId:"", chapterTitle:"",
      title: `${nm} — ${r[1]?.trim()||""}`, seq: ++sq, duration: r[1]?.trim()||"",
      summary: r[2]?.trim()||"", keywords: r[3]?.trim()||"" });
  }

  // summaries
  const sumSec = md.split("## 逐课摘要")[1] || "";
  const blocks = sumSec.split("### ");
  const sm: Record<string, string> = {};
  for (const b of blocks) {
    const lines = b.split("\n");
    const h = lines[0]?.trim()||"";
    const m = h.match(/^(.+?)\s*\(/);
    if (m) sm[m[1].trim()] = lines.slice(1).join("\n").trim();
  }
  for (const l of lss) {
    const bn = (l.title as string).split(" —")[0]?.trim()||"";
    if (sm[bn]) l.summary = sm[bn];
  }
  // assign chapters
  for (const l of lss) {
    for (const ch of chs) {
      const rng = ch.range as string;
      const num = parseInt((l.title as string).match(/伤寒论(\d+)/)?.[1]||"0");
      const rm = rng.match(/伤寒论(\d+)-伤寒论(\d+)/);
      if (rm && num >= parseInt(rm[1]) && num <= parseInt(rm[2])) {
        l.chapterId = ch.id as string;
        l.chapterTitle = ch.title as string;
      }
    }
  }

  const lIt = lss.map((l) => `
  { id:${S(l.id)}, chapterId:${S(l.chapterId)}, chapterTitle:${S(l.chapterTitle)},
    title:${S(l.title)}, seq:${l.seq}, duration:${S(l.duration)}, completed:false,
    summary:${S((l.summary as string)?.slice(0,200)||"")},
    content:${S((l.summary as string)?.slice(0,500)||"")},
    blackboards:[], keywords:${S(l.keywords)} }`);

  wr("lessons.ts", 'import { Lesson } from "../types";\n', `export const lessons: Lesson[] = [${lIt.join(",")}\n];`);

  const cIt = chs.map((ch) => `
  { id:${S(ch.id)}, title:${S(ch.title)}, order:${ch.order},
    description:${S(ch.description)},
    lessons: [] }`);

  wr("chapters.ts", 'import { Chapter } from "../types";\n', `export const chapters: Chapter[] = [${cIt.join(",")}\n];`);
}

// ── 3. Screenshots ────────────────────────────────────────

function buildScreenshots() {
  const files = {
    "screenshot-evidence.md":"shanghanlun",
    "jingui-screenshot-evidence.md":"jingui",
    "zhongjing-xinfa-screenshot-evidence.md":"zhongjing-xinfa",
    "clinical-cases-screenshot-evidence.md":"clinical-cases",
    "bagang-screenshot-evidence.md":"bagang",
    "fuyang-screenshot-evidence.md":"fuyang",
    "yijinjing-screenshot-evidence.md":"yijinjing",
    "huangdi-screenshot-evidence.md":"huangdi",
    "bencao-screenshot-evidence.md":"bencao",
    "acupuncture-screenshot-evidence.md":"acupuncture",
    "tianji-screenshot-evidence.md":"tianji",
  };
  const ss: Record<string, any>[] = [];
  let sid = 0;
  for (const [fn, mod] of Object.entries(files)) {
    const md = r(fn);
    if (!md) continue;
    let les = "";
    for (const line of md.split("\n")) {
      if (line.startsWith("## ") && !line.startsWith("## 分类")) { les = line.replace(/^##\s*/,"").trim(); continue; }
      const em = line.match(/^-\s*`([^`]+)`\s*\[([^\]]+)\]\s*(.+)/);
      if (em) {
        ss.push({ id: `ss-${++sid}`, module: mod, lesson: les,
          timestamp: em[1].trim(), categories: em[2].trim().split(/[,，]/).map((c) => c.trim()),
          description: em[3].trim(), path: "" });
        continue;
      }
      const pm = line.match(/-\s*截图路径[：:]\s*(.+)/);
      if (pm && ss.length > 0) ss[ss.length-1].path = pm[1].trim();
    }
  }

  const items = ss.map((s) => `
  { id:${S(s.id)}, module:${S(s.module)}, lesson:${S(s.lesson)},
    timestamp:${S(s.timestamp)}, categories:[${s.categories.map((c: string) => S(c)).join(",")}],
    description:${S(s.description)}, path:${S(s.path)} }`);

  wr("screenshots.ts", 'import { ScreenshotEntry } from "../types";\n', `export const screenshots: ScreenshotEntry[] = [${items.join(",")}\n];`);
}

// ── 4. Six Meridian Stages ───────────────────────────────

function buildSixMeridian() {
  const md = r("six-channel.md");
  const trs = parseTable(md);
  const stgs: Record<string, any>[] = [];

  for (const r of trs) {
    if (r[0] === "六经" || !r[0] || r.length < 3) continue;
    stgs.push({
      name: r[0]?.trim()||"",
      nature: r[1]?.trim()||"",
      symptoms: (r[2]?.trim()||"").split(/[，,；;、]/).map((s) => s.trim()).filter(Boolean),
      formulas: (r[3]?.trim()||"").split(/[，,、]/).map((s) => s.trim()).filter(Boolean),
      contra: r[4]?.trim()||"",
    });
  }

  const items = stgs.map((s) => `
  { id:${S("stage-"+s.name)}, name:${S(s.name)}, nature:${S(s.nature)},
    pathology:${S(s.nature)}, symptoms:[${s.symptoms.map((x: string) => S(x)).join(",")}],
    pulseCondition:"", classicFormulas:[${s.formulas.map((x: string) => S(x)).join(",")}],
    therapeutics:${S(s.contra)} }`);

  wr("sixMeridianStages.ts", 'import { SixMeridianStage } from "../types";\n', `export const sixMeridianStages: SixMeridianStage[] = [${items.join(",")}\n];`);
}

// ── 5. Symptom Routes ────────────────────────────────────

function buildSymptomRoutes() {
  const md = r("symptom-index.md");
  const trs = parseTable(md);
  const routes: Record<string, any>[] = [];

  for (const r of trs) {
    if (r[0] === "用户症状" || !r[0] || r.length < 2) continue;
    routes.push({
      symptom: r[0]?.trim()||"",
      watershed: r[1]?.trim()||"",
      patterns: (r[2]?.trim()||"").split(/[，,、]/).map((s) => s.trim()).filter(Boolean),
    });
  }

  const items = routes.map((r) => `
  { symptom:${S(r.symptom)}, watershed:${S(r.watershed)},
    patterns:[${r.patterns.map((p: string) => S(p)).join(",")}] }`);

  wr("symptomRoutes.ts", 'import { SymptomRoute } from "../types";\n', `export const symptomRoutes: SymptomRoute[] = [${items.join(",")}\n];`);
}

// ── main ──────────────────────────────────────────────────

console.log("🏗️  buildData — nihaisha MD → TypeScript\n");
console.log(`   数据源: ${REF}`);
console.log(`   输出:   ${OUT}\n`);

fs.mkdirSync(OUT, { recursive: true });

console.log("── 1. 方剂方证 ──"); buildFormulas();
console.log("\n── 2. 课次 + 章节 ──"); buildLessons();
console.log("\n── 3. 截图索引 ──"); buildScreenshots();
console.log("\n── 4. 六经辨证 ──"); buildSixMeridian();
console.log("\n── 5. 症状路由 ──"); buildSymptomRoutes();

console.log("\n✅ 数据管道完成\n");
