// Auto-generated by scripts/buildData.ts
import { Chapter } from "../types";

export const chapters: Chapter[] = [
  { id:"ch-1", title:"太阳病与经方基础", order:1,
    description:"伤寒论01-伤寒论05",
    lessons: [] },
  { id:"ch-2", title:"少阳病与复杂变证", order:2,
    description:"伤寒论06-伤寒论09",
    lessons: [] },
  { id:"ch-3", title:"阳明病与攻下大法", order:3,
    description:"伤寒论10-伤寒论12",
    lessons: [] },
  { id:"ch-4", title:"三阴病与危重救逆", order:4,
    description:"伤寒论13-伤寒论15",
    lessons: [] }
];
